const Data = {
    productItems: [
      {
        id: 7,
        cover: "./images/categories/Notebooks/Notebook_ASUS_X515EA.jpg",
        name: "Notebook ASUS X515EA",
        price: "109.500",
        discount: "25",
      },
      {
        id: 8,
        cover: "./images/categories/Notebooks/Notebook_ASUS_ZenBook_UX425_14.jpg",
        name: "Notebook ASUS ZenBook UX425",
        price: "250.950",
        discount: "10",
      },
      {
        id: 9,
        cover: "./images/categories/Notebooks/Notebook_Gamer_ASUS_TUF_FX506.jpg",
        name: "Notebook ASUS TUF FX506",
        price: "278.450",
        discount: "50 ",
      },
      {
        id: 10,
        cover: "./images/categories/Notebooks/Notebook_Gamer_Asus_TUF_FX516.jpg",
        name: "Notebook Gamer Asus TUF FX516",
        price: "340.000",
        discount: "10 ",
      },
      {
        id: 11,
        cover: "./images/categories/Notebooks/Notebook_Gamer_ASUS_TUF_F15.jpg",
        name: "Notebook ASUS TUF F15",
        price: "347.500",
        discount: "20 ",
      },
      {
        id: 12,
        cover: "./images/categories/Notebooks/Notebook_ASUS_ZenBook_DUO_TOUCH_UX482.jpg",
        name: "Notebook ASUS ZenBook",
        price: "502.000",
        discount: "20 ",
      },
      {
        id: 13,
        cover: "./images/categories/Notebooks/Notebook_Acer_Aspire_3.jpg",
        name: "Notebook Acer Aspire 3",
        price: "192.500",
        discount: "5 ",
      },
      {
        id: 14,
        cover: "./images/categories/Notebooks/Notebook_Gamer_Acer_NITRO_5.jpg",
        name: "Notebook Gamer Acer NITRO 5",
        price: "464.100",
        discount: "10",
      },
      {
        id: 15,
        cover: "./images/categories/cpu/Ryzen3-3200.jpg",
        name: "Ryzen 3 3200",
        price: "464.100",
        discount: "10",
        cat: 'cpu',
        subCat: 'amd',
      },
      {
        id: 16,
        cover: "./images/categories/cpu/Ryzen3-3200.jpg",
        name: "Ryzen 3 3200",
        price: "464.100",
        discount: "10",
        cat: 'cpu',
        subCat: 'amd',
      },
      {
        id: 17,
        cover: "./images/categories/cpu/Ryzen3-4100.jpg",
        name: "Ryzen 3 4100",
        price: "464.100",
        discount: "10",
        cat: 'cpu',
        subCat: 'amd',
      },
      {
        id: 18,
        cover: "./images/categories/cpu/Ryzen5-4500.jpg",
        name: "Ryzen 5 4500",
        price: "464.100",
        discount: "10",
        cat: 'cpu',
        subCat: 'amd',
      },
      {
        id: 19,
        cover: "./images/categories/cpu/Ryzen7-4750.jpg",
        name: "Ryzen 7 4750",
        price: "464.100",
        discount: "10",
        cat: 'cpu',
        subCat: 'amd',
      },
      {
        id: 20,
        cover: "./images/categories/cpu/ryzen7-7700.jpg",
        name: "Ryzen 7 7700",
        price: "464.100",
        discount: "10",
        cat: 'cpu',
        subCat: 'amd',
      },
      {
        id: 21,
        cover: "./images/categories/cpu/Intel-g4560.jpg",
        name: "Intel G4560",
        price: "464.100",
        discount: "10",
        cat: 'cpu',
        subCat: 'intel',
      },
      {
        id: 23,
        cover: "./images/categories/cpu/Intel-g4900.jpg",
        name: "Intel G4900",
        price: "464.100",
        discount: "10",
        cat: 'cpu',
        subCat: 'intel',
      },
      {
        id: 23,
        cover: "./images/categories/cpu/Intel-i3-10105.jpg",
        name: "Intel I3 10105",
        price: "464.100",
        discount: "10",
        cat: 'cpu',
        subCat: 'intel',
      },
      {
        id: 24,
        cover: "./images/categories/cpu/Intel-i5-12400.jpg",
        name: "Intel I5 12400",
        price: "464.100",
        discount: "10",
        cat: 'cpu',
        subCat: 'intel',
      },
      {
        id: 25,
        cover: "./images/categories/cpu/Intel-i7-12700.jpg",
        name: "Intel I7 12700",
        price: "464.100",
        discount: "10",
        cat: 'cpu',
        subCat: 'intel',
      },

      
    ],
}

export default Data;